### SEPS

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_excel("test3.xlsx")
df.head()

,Roll No.,Name,ED Test 1,ED Test 2,ED Test 3,EM Test 1,EM Test 2,EM Test 3,CP Test 1,CP Test 2,...,EP Test 1,EP Test 2,EP Test 3,ED total,EM total,CP total,FEE total,EP total,Total,results
0,KAT081BEI001,Aadarsh Pajiyar,0,6,11,8,8,33,11,8.0,...,8,11,26,17,49,42,35,45,188,52.222222
1,KAT081BEI002,Aasish Mainali,5,5,13,16,20,39,18,16.0,...,20,20,34,23,75,70,60,74,302,83.888889
2,KAT081BEI003,Akash Khatri Chhetri,10,8,16,20,16,40,8,0.0,...,12,11,23,34,76,31,38,46,225,62.500000
3,KAT081BEI004,Anup Kumal,8,8,16,10,8,27,16,12.0,...,10,4,19,32,45,57,27,33,194,53.888889
4,KAT081BEI005,Anusha Rai,6,7,11,8,5,20,10,6.0,...,4,3,9,24,33,32,22,16,127,35.277778


In [3]:
df.columns

Index(['Roll No.', 'Name', 'ED Test 1', 'ED Test 2', 'ED Test 3', 'EM Test 1',
       'EM Test 2', 'EM Test 3', 'CP Test 1', 'CP Test 2', 'CP Test 3',
       'FEE Test 1', 'FEE Test 2', 'FEE Test 3', 'EP Test 1', 'EP Test 2',
       'EP Test 3', 'ED total', 'EM total', 'CP total', 'FEE total',
       'EP total', 'Total', 'results'],
      dtype='object')

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 24 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Roll No.    40 non-null     object 
 1   Name        40 non-null     object 
 2   ED Test 1   40 non-null     int64  
 3   ED Test 2   40 non-null     int64  
 4   ED Test 3   40 non-null     int64  
 5   EM Test 1   40 non-null     int64  
 6   EM Test 2   40 non-null     int64  
 7   EM Test 3   40 non-null     int64  
 8   CP Test 1   40 non-null     int64  
 9   CP Test 2   39 non-null     float64
 10  CP Test 3   40 non-null     int64  
 11  FEE Test 1  40 non-null     int64  
 12  FEE Test 2  40 non-null     int64  
 13  FEE Test 3  40 non-null     int64  
 14  EP Test 1   40 non-null     int64  
 15  EP Test 2   40 non-null     int64  
 16  EP Test 3   40 non-null     int64  
 17  ED total    40 non-null     int64  
 18  EM total    40 non-null     int64  
 19  CP total    40 non-null     int

In [5]:
df['results'] = df['Total'].apply(lambda x: 'Pass' if x >= 144 else 'Fail')
X = df[['ED Test 1','ED Test 2','ED Test 3','EM Test 1','EM Test 2','EM Test 3','CP Test 1','CP Test 2','CP Test 3',
    'FEE Test 1','FEE Test 2','FEE Test 3','EP Test 1','EP Test 2','EP Test 3','ED total','EM total','CP total','FEE total',
    'EP total','Total']]
y = df['results']

In [6]:
print(X.isnull().sum())
print(y.isnull().sum())

ED Test 1     0
ED Test 2     0
ED Test 3     0
EM Test 1     0
EM Test 2     0
EM Test 3     0
CP Test 1     0
CP Test 2     1
CP Test 3     0
FEE Test 1    0
FEE Test 2    0
FEE Test 3    0
EP Test 1     0
EP Test 2     0
EP Test 3     0
ED total      0
EM total      0
CP total      0
FEE total     0
EP total      0
Total         0
dtype: int64
0


In [7]:
X = X.fillna(X.mean())

### LogisticRegression

In [8]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
x_train,x_test,y_train,y_test= train_test_split(X,y,test_size=0.2,random_state=42)
model= LogisticRegression()

In [9]:
model.fit(x_train,y_train)

,penalty,'l2'
,dual,False
,tol,0.0001
,C,1.0
,fit_intercept,True
,intercept_scaling,1
,class_weight,None
,random_state,None
,solver,'lbfgs'
,max_iter,100
,multi_class,'deprecated'


In [10]:
y_test

19    Pass
16    Fail
15    Pass
26    Pass
4     Fail
12    Pass
37    Pass
27    Pass
Name: results, dtype: object

In [11]:
y_pred= model.predict(x_test)
y_pred

array(['Fail', 'Pass', 'Pass', 'Fail', 'Pass', 'Pass', 'Pass', 'Pass'],
      dtype=object)

In [12]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [13]:
accuracy_score(y_test,y_pred)

0.5

In [14]:
confusion_matrix(y_test,y_pred)

array([[0, 2],
       [2, 4]])

In [15]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

        Fail       0.00      0.00      0.00         2
        Pass       0.67      0.67      0.67         6

    accuracy                           0.50         8
   macro avg       0.33      0.33      0.33         8
weighted avg       0.50      0.50      0.50         8



### Naive Bayes

In [16]:
from sklearn.naive_bayes import GaussianNB

In [17]:
model_NB= GaussianNB()
model_NB.fit(x_train,y_train)

,priors,None
,var_smoothing,1e-09


In [18]:
y_pred_NB= model_NB.predict(x_test)
y_pred_NB

array(['Fail', 'Fail', 'Pass', 'Fail', 'Fail', 'Pass', 'Pass', 'Pass'],
      dtype='<U4')

In [19]:
accuracy_score(y_test,y_pred_NB)

0.75

In [20]:
confusion_matrix(y_test,y_pred_NB)

array([[2, 0],
       [2, 4]])

In [21]:
print(classification_report(y_test,y_pred_NB))

              precision    recall  f1-score   support

        Fail       0.50      1.00      0.67         2
        Pass       1.00      0.67      0.80         6

    accuracy                           0.75         8
   macro avg       0.75      0.83      0.73         8
weighted avg       0.88      0.75      0.77         8



### Decision Tree

In [22]:
from sklearn.preprocessing import StandardScaler
scaler= StandardScaler()
x_train_scaled= scaler.fit_transform(x_train)
x_test_scaled= scaler.transform(x_test)

In [23]:
from sklearn.tree import DecisionTreeClassifier
model_DT= DecisionTreeClassifier(random_state=42)

In [24]:
model_DT.fit(x_train_scaled,y_train) # we used previously scaled data for decision tree

,criterion,'gini'
,splitter,'best'
,max_depth,None
,min_samples_split,2
,min_samples_leaf,1
,min_weight_fraction_leaf,0.0
,max_features,None
,random_state,42
,max_leaf_nodes,None
,min_impurity_decrease,0.0
,class_weight,None


In [25]:
y_pred_DT=model_DT.predict(x_test_scaled)
y_pred_DT

array(['Fail', 'Fail', 'Pass', 'Pass', 'Fail', 'Pass', 'Pass', 'Pass'],
      dtype=object)

In [26]:
accuracy_score(y_test,y_pred_DT)

0.875

In [27]:
confusion_matrix(y_test,y_pred_DT)

array([[2, 0],
       [1, 5]])

In [28]:
print(classification_report(y_test,y_pred_DT))

              precision    recall  f1-score   support

        Fail       0.67      1.00      0.80         2
        Pass       1.00      0.83      0.91         6

    accuracy                           0.88         8
   macro avg       0.83      0.92      0.85         8
weighted avg       0.92      0.88      0.88         8



### Random Forest

In [29]:
from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(
    n_estimators=100,     # number of trees
    max_depth=None,       # let trees grow fully
    random_state=42,
)

In [30]:
rf_model.fit(x_train,y_train)

,n_estimators,100
,criterion,'gini'
,max_depth,None
,min_samples_split,2
,min_samples_leaf,1
,min_weight_fraction_leaf,0.0
,max_features,'sqrt'
,max_leaf_nodes,None
,min_impurity_decrease,0.0
,bootstrap,True
,oob_score,False


In [31]:
y_pred_rf = rf_model.predict(x_test)
accuracy = accuracy_score(y_test, y_pred_rf)
accuracy

0.875

In [32]:
confusion_matrix(y_test,y_pred_rf)

array([[2, 0],
       [1, 5]])

In [33]:
print(classification_report(y_test,y_pred_rf))

              precision    recall  f1-score   support

        Fail       0.67      1.00      0.80         2
        Pass       1.00      0.83      0.91         6

    accuracy                           0.88         8
   macro avg       0.83      0.92      0.85         8
weighted avg       0.92      0.88      0.88         8

